config/routes.rb
Rails.application.routes.draw do

root 'users#index'
get 'show' => 'users#show'
get 'about' => 'pages#about'
get 'edit' =>'users#edit'
get 'delete' => 'users#delete'

	resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def index
	end


	def new
		@user=User.new
		@users=User.all
	end

	def show
		@users=User.all

	end

	def delete
		@user=User.find(params[:id])
		@user.delete

		redirect_to show_user_path

	end

	def edit
		@user = User.find(params[:id])
  		unless @user
    		flash[:error] = "User not found"
    		redirect_to root_path
  end
	end

	def create
		@user=User.new(params.require(:user).permit(:name, :email, :phone))
		if @user.save
			redirect_to new_user_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myproject1</title>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


     <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">PANEL</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active nav-link">
        <%= link_to "Index", root_path %>   <span class="sr-only">(current)</span>
      </li>
      <li class=" nav-item nav-link active ">
        <%= link_to "New User ", new_user_path %><span class="sr-only">(current)</span>
      </li>
      <li class="nav-item active nav-link">
        <%= link_to "Show Existing Users", show_path %><span class="sr-only">(current)</span>
      </li>
      
      
    </ul>
    
  </div>
</nav>

    <%= yield %>
  </body>
</html>

app/views/layouts/delete.html.erb
<br><br><br><br><h1>Deleted.</h1>

app/views/pages/about.html.erb
<h1>About Page</h1>

app/views/users/edit.html.erb
Edit Data
<hr>

  <%= form_for :user, url : user_path(@user), method: :patch do |f| %><br><br>  
	Name  <%= f.text_field :name %><br><br>
	Email <%= f.text_field :email %><br><br>
	Phone <%= f.text_field :phone %><br><br>	
	<%= f.submit({:class => 'btn btn-primary'}) %>
<% end -%>

<hr>

<!-- All UsersInfo<br><br>

<%if !@users.blank? %>
	<% for u in @users %>
		<%= u.name%> <%= u.email%> <%= u.phone%> <br>

	<% end %>

<% else %>

<% end %> -->

app/views/users/index.html.erb
<br><br><br><br><br><h1 align="center">This is The Home Page.</h1>

app/views/users/new.html.erb
USER INFO
<hr>

  <%= form_for @user do |f| %>
  
	Name  <%= f.text_field :name %><br><br>
	Email <%= f.text_field :email %><br><br>
	Phone <%= f.text_field :phone %><br><br>	
	<%= f.submit %>
<% end -%>

<hr>

<!-- All UsersInfo<br><br>

<%if !@users.blank? %>
	<% for u in @users %>
		<%= u.name%> <%= u.email%> <%= u.phone%> <br>

	<% end %>

<% else %>

<% end %> -->

app/views/users/show.html.erb
<br><br><br><br><br><br><h1 align='center'>All Users Info</h1><br><br>

<%if !@users.blank? %>
	<% for u in @users %>
		<%= u.id %><%= u.name%> <%= u.email%> <%= u.phone%> <hr><%= link_to "Edit", edit_path(@user), :class => 'btn-btn-default' %><hr><%= link_to "Delete", delete_path(@user),
		 method: :delete,
		 data: {confirm: "Are you sure ?"},		
		 :class => 'btn-btn-default' %><br><br><br>
	<% end %>

<% else %>

<% end %>